import { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { JourneyApiClient } from '../../api/client';
import { SafeQueryClientProvider } from '../SafeQueryClientProvider';
import { Modal } from '../common/Modal';
import { Button } from '../common/Button';
import { Badge } from '../common/Badge';
import { CloseButton } from '../common/CloseButton';

const apiClient = new JourneyApiClient();

export interface ParameterItem {
  key: string;
  name: string;
  category: 'event' | 'subject' | 'node' | 'experiment' | 'parameter';
  categoryLabel: string;
  description: string;
  token: string;
  exampleValue?: string;
  dataClassification?: string;
}

export interface ParameterModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectToken: (token: string) => void;
  targetFieldLabel?: string;
  customParameters?: ParameterItem[];
}

const DEFAULT_PARAMETERS: ParameterItem[] = [
  // Event Payload Fields
  {
    key: 'event.user_id',
    name: 'User ID',
    category: 'event',
    categoryLabel: 'Event Field',
    description: 'Unique identifier of the triggering user in event payload',
    token: '{{event.user_id}}',
    exampleValue: 'usr_8921a',
    dataClassification: 'PII',
  },
  {
    key: 'event.email',
    name: 'Triggering Email',
    category: 'event',
    categoryLabel: 'Event Field',
    description: 'User primary email address captured at event time',
    token: '{{event.email}}',
    exampleValue: 'alex@example.com',
    dataClassification: 'PII',
  },
  {
    key: 'event.amount',
    name: 'Order Amount ($)',
    category: 'event',
    categoryLabel: 'Event Field',
    description: 'Monetary value associated with the event transaction',
    token: '{{event.amount}}',
    exampleValue: '149.50',
    dataClassification: 'Internal',
  },
  {
    key: 'event.timestamp',
    name: 'Event Timestamp',
    category: 'event',
    categoryLabel: 'Event Field',
    description: 'ISO-8601 UTC timestamp when event occurred',
    token: '{{event.timestamp}}',
    exampleValue: '2026-08-05T14:32:00Z',
    dataClassification: 'Public',
  },

  // Subject Attributes
  {
    key: 'subject.tier',
    name: 'Subscription Tier',
    category: 'subject',
    categoryLabel: 'Subject Attribute',
    description: 'Customer entitlement tier (Free, Pro, Enterprise)',
    token: '{{subject.tier}}',
    exampleValue: 'Enterprise',
    dataClassification: 'Internal',
  },
  {
    key: 'subject.first_name',
    name: 'First Name',
    category: 'subject',
    categoryLabel: 'Subject Attribute',
    description: 'Subject given name from profile directory',
    token: '{{subject.first_name}}',
    exampleValue: 'Alex',
    dataClassification: 'PII',
  },
  {
    key: 'subject.lifetime_value',
    name: 'Customer LTV ($)',
    category: 'subject',
    categoryLabel: 'Subject Attribute',
    description: 'Total historical revenue generated by this subject',
    token: '{{subject.lifetime_value}}',
    exampleValue: '4250.00',
    dataClassification: 'Sensitive',
  },

  // Node Outputs
  {
    key: 'node.http_status',
    name: 'HTTP Response Code',
    category: 'node',
    categoryLabel: 'Node Output',
    description: 'Status code returned by HTTP Action step execution',
    token: '{{node.webhook_1.status}}',
    exampleValue: '200',
    dataClassification: 'System',
  },
  {
    key: 'node.coupon_code',
    name: 'Generated Coupon Code',
    category: 'node',
    categoryLabel: 'Node Output',
    description: 'Promotional discount token issued by previous action node',
    token: '{{node.discount_gen.code}}',
    exampleValue: 'VIP-SUMMER-20',
    dataClassification: 'Internal',
  },

  // Experiment Context
  {
    key: 'experiment.variant',
    name: 'Experiment Variant Assigned',
    category: 'experiment',
    categoryLabel: 'Experiment Context',
    description: 'Active A/B variant assignment (control, variant_a, variant_b)',
    token: '{{experiment.variant}}',
    exampleValue: 'variant_b',
    dataClassification: 'Internal',
  },
];

function ParameterModalInner({
  isOpen,
  onClose,
  onSelectToken,
  targetFieldLabel,
  customParameters = [],
}: ParameterModalProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');

  const { data: fetchedMetrics } = useQuery({
    queryKey: ['catalogs', 'metrics'],
    queryFn: async () => apiClient.getCatalogMetrics(),
    enabled: isOpen,
  });

  const { data: fetchedAttributes } = useQuery({
    queryKey: ['catalogs', 'attributes'],
    queryFn: async () => apiClient.getCatalogAttributes(),
    enabled: isOpen,
  });

  const allParameters = useMemo(() => {
    const list = [...customParameters, ...DEFAULT_PARAMETERS];

    if (fetchedMetrics) {
      fetchedMetrics.forEach((m) => {
        if (!list.some((p) => p.token === `{{metric.${m.id}}}`)) {
          list.push({
            key: `metric.${m.id}`,
            name: m.name || m.id,
            category: 'parameter',
            categoryLabel: 'Catalog Metric',
            description: m.description || `Catalog aggregation metric (${m.aggregation_type})`,
            token: `{{metric.${m.id}}}`,
            exampleValue: '12',
            dataClassification: 'Internal',
          });
        }
      });
    }

    if (fetchedAttributes) {
      fetchedAttributes.forEach((a) => {
        if (!list.some((p) => p.token === `{{subject.${a.id}}}`)) {
          list.push({
            key: `subject.${a.id}`,
            name: a.name || a.id,
            category: 'subject',
            categoryLabel: 'Catalog Attribute',
            description: a.description || `Catalog subject attribute (${a.data_type})`,
            token: `{{subject.${a.id}}}`,
            exampleValue: 'value',
            dataClassification: a.is_pii ? 'PII' : 'Internal',
          });
        }
      });
    }

    return list;
  }, [customParameters, fetchedMetrics, fetchedAttributes]);

  const filteredParameters = useMemo(() => {
    return allParameters.filter((param) => {
      const matchesCategory =
        selectedCategory === 'all' || param.category === selectedCategory;

      const q = searchQuery.toLowerCase().trim();
      const matchesSearch =
        !q ||
        param.name.toLowerCase().includes(q) ||
        param.token.toLowerCase().includes(q) ||
        param.description.toLowerCase().includes(q) ||
        param.categoryLabel.toLowerCase().includes(q);

      return matchesCategory && matchesSearch;
    });
  }, [allParameters, searchQuery, selectedCategory]);

  if (!isOpen) return null;

  const categories = [
    { id: 'all', label: 'All Items' },
    { id: 'event', label: 'Event Fields' },
    { id: 'subject', label: 'Subject Attributes' },
    { id: 'node', label: 'Node Outputs' },
    { id: 'experiment', label: 'Experiment Context' },
    { id: 'parameter', label: 'Shared Parameters' },
  ];

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Parameter Library"
      subtitle={
        targetFieldLabel
          ? `Insert dynamic parameter token into field "${targetFieldLabel}"`
          : 'Insert dynamic runtime tokens (event, subject, node outputs, experiments)'
      }
      icon="token"
      iconAccentColor="#4cd7f6"
      maxWidth="3xl"
      maxHeight="75vh"
      testId="parameter-modal"
      ariaLabelledBy="parameter-modal-title"
      bodyClassName="p-0 flex-1 min-h-0 flex flex-col overflow-hidden text-xs font-['Outfit',sans-serif]"
      footer={
        <div className="flex items-center justify-between w-full">
          <span className="text-xs text-[#908fa0] font-mono">
            Showing {filteredParameters.length} parameters
          </span>
          <Button variant="secondary-dark" onClick={onClose}>
            Close
          </Button>
        </div>
      }
    >
      {/* Search & Category Filter Controls */}
      <div className="p-4 sm:p-5 border-b border-[#464554] bg-[#171b26]/80 backdrop-blur-md shrink-0">
        <div className="relative mb-3">
          <input
            type="text"
            placeholder="Search parameters by name, token (e.g. {{event.user_id}}), description..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            data-testid="parameter-search-input"
            autoFocus
            className="w-full px-4 pr-8 py-2.5 rounded-none bg-[#11141d] border border-[#464554] text-[#dfe2f1] placeholder-[#64748b] text-xs focus:outline-none focus:border-[#4cd7f6] focus:ring-1 focus:ring-[#4cd7f6] font-['Outfit',sans-serif]"
          />
          {searchQuery && (
            <CloseButton
              onClick={() => setSearchQuery('')}
              ariaLabel="Clear search input"
              size="sm"
              className="absolute right-2 top-1/2 -translate-y-1/2"
            />
          )}
        </div>

        {/* Category Tabs */}
        <div
          className="flex gap-2 overflow-x-auto pb-1 max-w-full"
          role="tablist"
          aria-label="Parameter Categories"
        >
          {categories.map((cat) => (
            <button
              key={cat.id}
              role="tab"
              aria-selected={selectedCategory === cat.id}
              data-testid={`param-category-tab-${cat.id}`}
              onClick={() => setSelectedCategory(cat.id)}
              className={`px-3 py-1.5 rounded-none text-xs font-semibold transition-all cursor-pointer ${
                selectedCategory === cat.id
                  ? 'bg-[#262a35] text-[#c0c1ff] border border-[#c0c1ff]/40 font-bold shadow-sm'
                  : 'bg-[#1c1f2a] text-[#908fa0] hover:text-white hover:bg-[#262a35] border border-[#464554]'
              }`}
            >
              {cat.label}
            </button>
          ))}
        </div>
      </div>

      {/* Parameter List Content */}
      <div className="flex-1 min-h-0 overflow-y-auto p-4 sm:p-5 space-y-3">
        {filteredParameters.length === 0 ? (
          <div
            className="text-center py-12 text-[#908fa0] text-xs"
            data-testid="no-parameters-found"
          >
            <div className="text-3xl mb-2">🔎</div>
            <div className="font-semibold text-[#dfe2f1]">No parameters match your search</div>
            <div className="text-[11px] text-[#908fa0] mt-1">
              Try searching for a different token or category tab.
            </div>
          </div>
        ) : (
          <div className="flex flex-col gap-3">
            {filteredParameters.map((param) => (
              <div
                key={param.key}
                data-testid={`param-item-${param.key}`}
                className="flex items-center justify-between p-4 rounded-none border border-[#464554] bg-[#11141d] hover:border-[#4cd7f6]/40 hover:bg-[#171b26] transition-all group"
              >
                <div className="flex-1 pr-4">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="font-semibold text-sm text-white font-['Outfit']">
                      {param.name}
                    </span>
                    <Badge variant="neutral">{param.categoryLabel}</Badge>
                    {param.dataClassification === 'PII' && (
                      <Badge variant="amber">PII</Badge>
                    )}
                    {param.dataClassification === 'Sensitive' && (
                      <Badge variant="rose">Sensitive</Badge>
                    )}
                  </div>

                  <div className="mt-1 text-xs text-[#908fa0]">
                    {param.description}
                  </div>

                  <div className="mt-2 flex items-center gap-2 font-mono">
                    <code className="text-xs px-2 py-0.5 rounded-none bg-[#4cd7f6]/10 text-[#4cd7f6] border border-[#4cd7f6]/30 font-bold">
                      {param.token}
                    </code>
                    {param.exampleValue && (
                      <span className="text-[11px] text-[#908fa0]">
                        e.g. <em>{param.exampleValue}</em>
                      </span>
                    )}
                  </div>
                </div>

                <Button
                  type="button"
                  variant="secondary-dark"
                  size="sm"
                  icon="add_circle"
                  onClick={() => {
                    onSelectToken(param.token);
                    onClose();
                  }}
                  data-testid={`insert-token-btn-${param.key}`}
                  className="shrink-0 text-xs px-3.5 py-2"
                >
                  Insert Param
                </Button>
              </div>
            ))}
          </div>
        )}
      </div>
    </Modal>
  );
}

export function ParameterModal(props: ParameterModalProps) {
  return (
    <SafeQueryClientProvider>
      <ParameterModalInner {...props} />
    </SafeQueryClientProvider>
  );
}
